import { useState } from 'react';

const dummyReports = [
  { id: 2087, title: 'Multiple web server 400 error codes from same source ip', tenant: 'Universitas Indonesia', agent: 'Wazuh-Agent-UI-01', time: '2026-08-19 14:22:00' },
  { id: 2086, title: 'SSH Brute Force Attempt Detected', tenant: 'Institut Teknologi Bandung', agent: 'Wazuh-Agent-ITB-01', time: '2026-08-19 12:15:00' },
  { id: 2085, title: 'Suspicious PowerShell Execution', tenant: 'Universitas Gadjah Mada', agent: 'Wazuh-Agent-UGM-02', time: '2026-08-18 09:30:00' },
  { id: 2084, title: 'Malware downloaded via browser', tenant: 'Institut Pertanian Bogor', agent: 'Wazuh-Agent-IPB-01', time: '2026-08-17 18:45:00' },
  { id: 2083, title: 'Multiple failed logins for Admin account', tenant: 'Universitas Airlangga', agent: 'Wazuh-Agent-UNAIR-01', time: '2026-08-16 22:10:00' },
  { id: 2082, title: 'Unauthorized access to restricted directory', tenant: 'Universitas Indonesia', agent: 'Wazuh-Agent-UI-02', time: '2026-08-15 11:05:00' },
];

export default function ReportsView({ setActiveView }) {
  const [search, setSearch] = useState('');
  const [showFilters, setShowFilters] = useState(false);
  
  const [filterTenant, setFilterTenant] = useState('');
  const [filterAgent, setFilterAgent] = useState('');
  const [filterTime, setFilterTime] = useState('');

  const filteredReports = dummyReports.filter(report => {
    const matchSearch = report.title.toLowerCase().includes(search.toLowerCase()) || report.id.toString().includes(search);
    const matchTenant = filterTenant ? report.tenant === filterTenant : true;
    const matchAgent = filterAgent ? report.agent === filterAgent : true;
    // time filtering logic is just string includes for simplicity in this dummy view
    const matchTime = filterTime ? report.time.includes(filterTime) : true;
    return matchSearch && matchTenant && matchAgent && matchTime;
  });

  return (
    <div className="max-w-7xl mx-auto block fade-in flex flex-col h-full">
      <header className="mb-8 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <button 
              onClick={() => setActiveView && setActiveView('view-dashboard')}
              className="text-slate-400 hover:text-slate-900 transition-colors text-sm font-medium"
            >
              <i className="fa-solid fa-arrow-left mr-1"></i> Back to Dashboard
            </button>
          </div>
          <h2 className="text-2xl font-semibold text-slate-900 tracking-tight">Analyzed Reports</h2>
          <p className="text-slate-500 text-sm mt-1">List of all reports generated by the analysis engine.</p>
        </div>
      </header>

      <div className="mb-6 flex flex-col gap-4">
        <div className="flex items-center gap-3">
          <div className="relative flex-1 max-w-md">
            <i className="fa-solid fa-search absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 text-sm"></i>
            <input 
              type="text" 
              placeholder="Search by ID or Title..." 
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full shadcn-input pl-9 pr-4 py-2"
            />
          </div>
          <button 
            onClick={() => setShowFilters(!showFilters)}
            className={`px-4 py-2 text-sm rounded-md border transition-colors flex items-center gap-2 ${
              showFilters ? 'bg-slate-100 border-slate-300 text-slate-900' : 'bg-white border-slate-200 text-slate-600 hover:bg-slate-50'
            }`}
          >
            <i className="fa-solid fa-filter text-xs"></i> Filters
          </button>
        </div>

        {showFilters && (
          <div className="p-4 border border-slate-200 rounded-lg bg-slate-50 grid grid-cols-1 sm:grid-cols-3 gap-4 fade-in">
            <div>
              <label className="block text-xs font-medium text-slate-700 mb-1">Tenant</label>
              <select 
                value={filterTenant} 
                onChange={(e) => setFilterTenant(e.target.value)}
                className="w-full shadcn-input px-3 py-2 text-sm bg-white"
              >
                <option value="">All Tenants</option>
                <option value="Universitas Indonesia">Universitas Indonesia</option>
                <option value="Institut Teknologi Bandung">Institut Teknologi Bandung</option>
                <option value="Universitas Gadjah Mada">Universitas Gadjah Mada</option>
                <option value="Institut Pertanian Bogor">Institut Pertanian Bogor</option>
                <option value="Universitas Airlangga">Universitas Airlangga</option>
              </select>
            </div>
            <div>
              <label className="block text-xs font-medium text-slate-700 mb-1">Agent</label>
              <input 
                type="text" 
                placeholder="e.g. Wazuh-Agent-UI-01" 
                value={filterAgent}
                onChange={(e) => setFilterAgent(e.target.value)}
                className="w-full shadcn-input px-3 py-2 text-sm bg-white"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-slate-700 mb-1">Time (YYYY-MM-DD)</label>
              <input 
                type="date" 
                value={filterTime}
                onChange={(e) => setFilterTime(e.target.value)}
                className="w-full shadcn-input px-3 py-2 text-sm bg-white cursor-pointer"
              />
            </div>
          </div>
        )}
      </div>

      <div className="shadcn-card overflow-hidden flex-1 mb-6">
        <div className="overflow-x-auto h-full">
          <table className="w-full text-left text-sm text-slate-600">
            <thead className="bg-slate-50 border-b border-slate-200 text-xs uppercase font-semibold text-slate-500 sticky top-0">
              <tr>
                <th className="px-6 py-4">Report Details</th>
                <th className="px-6 py-4">Tenant / Agent</th>
                <th className="px-6 py-4 text-right">Time</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredReports.map(report => (
                <tr key={report.id} className="hover:bg-slate-50 transition-colors group cursor-pointer">
                  <td className="px-6 py-4">
                    <div className="font-semibold text-slate-900 mb-1">#{report.id} - {report.title}</div>
                    <div className="text-xs text-blue-600 opacity-0 group-hover:opacity-100 transition-opacity">View Full Report &rarr;</div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="font-medium text-slate-800">{report.tenant}</div>
                    <div className="text-xs text-slate-500 mt-0.5"><i className="fa-solid fa-shield-halved mr-1 text-[10px]"></i>{report.agent}</div>
                  </td>
                  <td className="px-6 py-4 text-right whitespace-nowrap text-slate-500 font-mono text-xs">
                    {report.time}
                  </td>
                </tr>
              ))}
              {filteredReports.length === 0 && (
                <tr>
                  <td colSpan="3" className="px-6 py-12 text-center text-slate-500">
                    No reports match your filters.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
